cookie:
  expiry_days: 30
  key: fatura_key_123456789
  name: fatura_cookie
credentials:
  usernames:
    anavarela:
      email: anabarrosvarela@gmail.com
      name: Ana Maria Barros Varela
      password: $2b$12$OdBNqetP3enkIFvsZ8y3eOGnW7ExrAvpmmYaOq3TLzMxlVbAVko2O
    juliaabreu:
      email: juliaabreu2002@gmail.com
      name: Julia Abreu
      password: $2b$12$OdBNqetP3enkIFvsZ8y3eOGnW7ExrAvpmmYaOq3TLzMxlVbAVko2O
    carolmello:
      email: carolmferreira2002@outlook.com
      name: carolina de mello ferreira
      password: $2b$12$OdBNqetP3enkIFvsZ8y3eOGnW7ExrAvpmmYaOq3TLzMxlVbAVko2O
preauthorized: null
