credentials:
  usernames:
    anavarela:
      email: anabarrosvarela@gmail.com
      name: Ana Maria Barros Varela
      password: $2b$12$YKjjkMPJcPgVWQu4oCfFwOhVJCNHxQQhQlTILHyQzQWJqQGBJKVFi
    juliaabreu:
      email: juliaabreu2002@gmail.com
      name: Julia Abreu
      password: $2b$12$YKjjkMPJcPgVWQu4oCfFwOhVJCNHxQQhQlTILHyQzQWJqQGBJKVFi
cookie:
  expiry_days: 30
  key: fatura_key_123456789
  name: fatura_cookie
